/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRegistryRouteImport } from './routes/docs/registry'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsCliRouteImport } from './routes/docs/cli'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRegistryRoute = DocsRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/cli': typeof DocsCliRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/registry': typeof DocsRegistryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/cli': typeof DocsCliRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/registry': typeof DocsRegistryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/cli': typeof DocsCliRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/registry': typeof DocsRegistryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/cli'
    | '/docs/getting-started'
    | '/docs/registry'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/docs/cli' | '/docs/getting-started' | '/docs/registry'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/cli'
    | '/docs/getting-started'
    | '/docs/registry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/registry': {
      id: '/docs/registry'
      path: '/registry'
      fullPath: '/docs/registry'
      preLoaderRoute: typeof DocsRegistryRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsCliRoute: typeof DocsCliRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsRegistryRoute: typeof DocsRegistryRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCliRoute: DocsCliRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsRegistryRoute: DocsRegistryRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
