/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Generated by `openapi-typescript` from the registry's OpenAPI spec at
 * `/api-docs/openapi.json`.  Regenerate with:
 *
 *   REGISTRY_URL=https://tsx-tsnv.onrender.com bun run --filter @tsx/api-types gen
 *
 * This file is committed so the monorepo always has a valid baseline.
 * CI regenerates it on every push to main to keep it in sync.
 */

export interface paths {
  "/health": {
    get: {
      responses: { 200: { content: { "application/json": { ok: boolean; service: string; version: string; db: string } } } }
    }
  }
  "/v1/stats": {
    get: {
      responses: { 200: { content: { "application/json": components["schemas"]["RegistryStats"] } } }
    }
  }
  "/v1/search": {
    get: {
      parameters: { query?: { q?: string; lang?: string; sort?: string; page?: number; size?: number } }
      responses: { 200: { content: { "application/json": components["schemas"]["SearchResult"] } } }
    }
  }
  "/v1/packages": {
    get: {
      parameters: { query?: { sort?: string; limit?: number } }
      responses: { 200: { content: { "application/json": components["schemas"]["Package"][] } } }
    }
  }
  "/v1/packages/{name}": {
    get: {
      parameters: { path: { name: string } }
      responses: {
        200: { content: { "application/json": components["schemas"]["Package"] } }
        404: { content: { "application/json": components["schemas"]["ApiError"] } }
      }
    }
    put: {
      parameters: { path: { name: string } }
      responses: { 200: { content: { "application/json": { ok: boolean } } } }
    }
    delete: {
      parameters: { path: { name: string } }
      responses: { 200: { content: { "application/json": { ok: boolean } } } }
    }
  }
  "/v1/packages/{name}/versions": {
    get: {
      parameters: { path: { name: string } }
      responses: { 200: { content: { "application/json": components["schemas"]["PackageVersion"][] } } }
    }
  }
  "/v1/packages/{name}/readme": {
    get: {
      parameters: { path: { name: string } }
      responses: { 200: { content: { "text/markdown": string } }; 204: never }
    }
    put: {
      parameters: { path: { name: string } }
      requestBody: { content: { "text/markdown": string } }
      responses: { 200: { content: { "application/json": { ok: boolean } } } }
    }
  }
  "/v1/packages/{name}/stats/downloads": {
    get: {
      parameters: { path: { name: string }; query?: { days?: number } }
      responses: { 200: { content: { "application/json": components["schemas"]["DailyDownloads"][] } } }
    }
  }
  "/v1/packages/{name}/{version}/tarball": {
    get: {
      parameters: { path: { name: string; version: string } }
      responses: { 200: { content: { "application/gzip": Blob } } }
    }
  }
  "/v1/packages/{name}/deprecate": {
    put: {
      parameters: { path: { name: string } }
      requestBody: { content: { "application/json": { message?: string | null } } }
      responses: { 200: { content: { "application/json": { ok: boolean } } } }
    }
  }
  "/v1/packages/{name}/versions/{version}": {
    delete: {
      parameters: { path: { name: string; version: string } }
      responses: { 200: { content: { "application/json": { ok: boolean; yanked: string } } } }
    }
  }
  "/v1/packages/publish": {
    post: {
      requestBody: { content: { "multipart/form-data": { name: string; version: string; manifest: string; tarball: Blob } } }
      responses: {
        201: { content: { "application/json": components["schemas"]["PublishResult"] } }
        400: { content: { "application/json": components["schemas"]["ApiError"] } }
        401: { content: { "application/json": components["schemas"]["ApiError"] } }
        429: { content: { "application/json": components["schemas"]["ApiError"] } }
      }
    }
  }
  "/v1/webhooks": {
    get: {
      responses: { 200: { content: { "application/json": components["schemas"]["Webhook"][] } } }
    }
    post: {
      responses: {
        201: { content: { "application/json": components["schemas"]["Webhook"] } }
        400: { content: { "application/json": components["schemas"]["ApiError"] } }
      }
    }
  }
  "/v1/webhooks/{id}": {
    delete: {
      parameters: { path: { id: number } }
      responses: { 200: { content: { "application/json": { ok: boolean } } } }
    }
  }
  "/v1/admin/audit-log": {
    get: {
      parameters: { query?: { limit?: number } }
      responses: { 200: { content: { "application/json": components["schemas"]["AuditEntry"][] } } }
    }
  }
  "/v1/admin/rate-limits": {
    get: {
      responses: { 200: { content: { "application/json": components["schemas"]["RateLimitEntry"][] } } }
    }
  }
}

export interface components {
  schemas: {
    Package: {
      name: string
      version: string
      description: string
      author: string
      license: string
      tags: string[]
      tsx_min: string
      created_at: string
      updated_at: string
      download_count: number
      star_count?: number
      deprecated_message?: string
      lang?: string
      runtime?: string
      provides?: string[]
      integrates_with?: string[]
    }
    PackageVersion: {
      version: string
      published_at: string
      download_count: number
    }
    SearchResult: {
      packages: components["schemas"]["Package"][]
      total: number
      page: number
      per_page: number
    }
    RegistryStats: {
      total_packages: number
      total_downloads: number
      total_versions: number
      packages_this_week: number
    }
    DailyDownloads: {
      date: string
      downloads: number
    }
    PublishResult: {
      name: string
      version: string
      checksum: string
      tarball_url: string
    }
    AuditEntry: {
      id: number
      action: string
      package_name: string
      version?: string
      author_name?: string
      ip_address?: string
      created_at: string
    }
    RateLimitEntry: {
      ip: string
      requests: number
      limit: number
      blocked: boolean
      window_secs_remaining: number
    }
    Webhook: {
      id: number
      owner_id: string
      url: string
      secret?: string | null
      events: string[]
      active: boolean
      created_at: string
    }
    ApiError: {
      error: string
    }
  }
}
